# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMainWindow


class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QPlainTextEdit {\n"
                                 "    background-color: rgb(85, 85, 85);\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "    border: none;\n"
                                 "    font: 14pt \"DokChampa\";\n"
                                 "}\n"
                                 "\n"
                                 "QMenuBar {\n"
                                 "    background-color: rgb(102, 102, 102);\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "}\n"
                                 "\n"
                                 "QMenuBar::item {\n"
                                 "    background-color: rgb(110, 110, 110);\n"
                                 "}\n"
                                 "\n"
                                 "QMenuBar::item:hover {\n"
                                 "    background-color: rgb(119, 119, 119);\n"
                                 "}\n"
                                 "\n"
                                 "QMenuBar::item:pressed {\n"
                                 "    background-color: rgb(85, 85, 85);\n"
                                 "}\n"
                                 "\n"
                                 "QMenu {\n"
                                 "    color: rgb(255, 255, 255);\n"
                                 "    background-color: rgb(119, 119, 119);\n"
                                 "}\n"
                                 "\n"
                                 "QMenu:hover {\n"
                                 "    background-color: rgb(136, 136, 136);\n"
                                 "}\n"
                                 "\n"
                                 "QMenu:pressed {\n"
                                 "    background-color: rgb(102, 102, 102);\n"
                                 "}\n"
                                 "QScrollBar {"
                                 "    width: 15px;"
                                 "    margin: 15px 0 15px 0;"
                                 "    background: #32CC99;"
                                 "}"
                                 "QScrollBar::handle {"
                                 "    border: 10px solid grey;"
                                 "    background: white;"
                                 "    min-height: 10px;"
                                 "}"
                                 "QScrollBar::add-line:vertical {"
                                 "    border: 2px solid grey;"
                                 "    background: none;"
                                 "    height: 15px;"
                                 "    subcontrol-position: bottom;"
                                 "    subcontrol-origin: margin;"
                                 "}"
                                 "QScrollBar::sub-line:vertical {"
                                 "    border: 2px solid grey;"
                                 "    background: none;"
                                 "    height: 15px;"
                                 "    subcontrol-position: top;"
                                 "    subcontrol-origin: margin;"
                                 "}"
                                 "QScrollBar::up-arrow:vertical {"
                                 "    subcontrol-position: bottom;"
                                 "    subcontrol-origin: margin;"
                                 "    {upArrow}"
                                 "}"
                                 "QScrollBar::down-arrow:vertical {"
                                 "    subcontrol-position: bottom;"
                                 "    subcontrol-origin: margin;"
                                 "    {downArrow}"
                                 "}"
                                 "QScrollBar::left-arrow:vertical {"
                                 "    subcontrol-position: bottom;"
                                 "    subcontrol-origin: margin;"
                                 "    {leftArrow}"
                                 "}"
                                 "QScrollBar::right-arrow:vertical {"
                                 "    subcontrol-position: bottom;"
                                 "    subcontrol-origin: margin;"
                                 "    {rightArrow}"
                                 "}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.text_input = QtWidgets.QPlainTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.text_input.sizePolicy().hasHeightForWidth())
        self.text_input.setSizePolicy(sizePolicy)
        self.text_input.setObjectName("text_input")
        self.horizontalLayout.addWidget(self.text_input)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menubar.setStyleSheet("")
        self.menubar.setObjectName("menubar")
        self.file = QtWidgets.QMenu(self.menubar)
        self.file.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.file.setStyleSheet("")
        self.file.setObjectName("file")
        MainWindow.setMenuBar(self.menubar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.new_0 = QtWidgets.QAction(MainWindow)
        self.new_0.setObjectName("new_0")
        self.open = QtWidgets.QAction(MainWindow)
        self.open.setObjectName("open")
        self.save = QtWidgets.QAction(MainWindow)
        self.save.setObjectName("save")
        self.save_as = QtWidgets.QAction(MainWindow)
        self.save_as.setObjectName("save_as")
        self.close = QtWidgets.QAction(MainWindow)
        self.close.setObjectName("close")
        self.file.addAction(self.new_0)
        self.file.addAction(self.open)
        self.file.addAction(self.save)
        self.file.addAction(self.save_as)
        self.file.addAction(self.close)
        self.menubar.addAction(self.file.menuAction())

        self.window_title = "Text Editor"
        self.opened_file = ''

        self.add_functions()
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", self.window_title))
        self.text_input.setPlaceholderText(
            _translate("MainWindow", "Enter text..."))
        self.file.setTitle(_translate("MainWindow", "File"))
        self.actionFile.setText(_translate("MainWindow", "Open File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.new_0.setText(_translate("MainWindow", "New"))
        self.open.setText(_translate("MainWindow", "Open..."))
        self.save.setText(_translate("MainWindow", "Save"))
        self.save_as.setText(_translate("MainWindow", "Save As..."))
        self.close.setText(_translate("MainWindow", "Close"))

    def add_functions(self):
        self.new_0.triggered.connect(self.create_new_file)
        self.open.triggered.connect(self.open_file)
        self.save.triggered.connect(self.save_file)
        self.save_as.triggered.connect(self.save_file_as)
        self.close.triggered.connect(self.close_file)

    def create_new_file(self):
        self.opened_file = 'untitled.txt'
        with open(self.opened_file, 'w'):
            self.text_input.setPlainText('')

    def open_file(self):
        self.opened_file, _ = QFileDialog.getOpenFileName(
            self, "Open File", ".", "Text Files (*.txt);;All Files (*)")
        try:
            with open(self.opened_file, "r") as f:
                contents = f.read()
                self.text_input.setPlainText(contents)
        except:
            pass

    def save_file(self):
        try:
            with open(self.opened_file, 'w') as f:
                f.write(self.text_input.toPlainText())
        except FileNotFoundError:
            self.opened_file, _ = QFileDialog.getSaveFileName(
                self, "Save File", ".", "Text Files (*.txt);;All Files (*)")
            try:
                with open(self.opened_file, 'w') as f:
                    f.write(self.text_input.toPlainText())
            except FileNotFoundError:
                pass

    def save_file_as(self):
        self.opened_file, _ = QFileDialog.getSaveFileName(
            self, "Save File As", ".", "Text Files (*.txt);;All Files (*)")
        try:
            with open(self.opened_file, 'w') as f:
                f.write(self.text_input.toPlainText())
        except FileNotFoundError:
            pass

    def close_file(self):
        self.opened_file = ''
        self.text_input.setPlainText('')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
